# Generated by Django 3.1.1 on 2020-09-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='cbody',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name_text',
            new_name='cname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
